### ISSUE TITLE
A2C does not converge on Pong

### ISSUE THREAD

**Issue by indrasweb** [Officium/RL-Experiments#10]
I've been struggling to find an A2C implementation that learns anything at all on Pong and Breakout.
I forked your repo and hoped it would be different, but for some reason, it doesn't seem to learn anything.
I left all the defaults the same, ran for 3M timesteps, but changed the logging rate to prevent colab from crashing.

https://colab.research.google.com/drive/1oQpgRNUIpTnVlblrm9SMBVxWWDAr75Y-

Could you have a look please :)
Thanks

**Comment by Officium** [comment]
The differences in code do not matter. We need to check the system environment setting. First of all, do you use Python 3?  Python 2 is not under testing. Furthermore, currently, in default setting, the `nenv` depends on the number of CPU cores. In your experiment, `nenv` is set to 2. As a result, the actual batch_size is `timestep_per_batch * nenv = 10`, which is too small. Increase this parameter, e.g., using `nenv=8`, may help decorrelate samples in the same batch, and also lead a larger batch_size to make the training more stable.
