### ISSUE TITLE
your's usage is not useful at all!

### ISSUE THREAD

**Issue by THSWind** [Officium/RL-Experiments#11]
When I run this as your documentation:
`python run.py --env=CartPole-v1 --algorithm=dqn --number_timesteps=1e5`

I get:
![image](https://user-images.githubusercontent.com/42888230/103776831-fc06ed80-506a-11eb-8981-c32dafd55a73.png)

**Comment by Officium** [comment]
Thank you! I have already fix the `README` by adding `--env_type=classic_control` to the usage.
