### ISSUE TITLE
PPO version

### ISSUE THREAD

**Issue by uvipen** [Officium/RL-Experiments#9]
Could you specify, whether your PPO is PPO1 or PPO 2. Thank you :)

**Comment by Officium** [comment]
As described in https://github.com/openai/baselines/issues/485, the main improvement of PPO2 is the parallel sampling. In OpenAI's implementation, the parallelization is provided by GPU+VecEnv or MPI. In this repo, we only supports the former parallelization. You can specify `--nenv=1` as PPO1 or using default setting (--nenv=num_of_cpus) as PPO2.
